/* global Buffer */
// A PNG reader for the composition suite's pixel assertions.
//
// The og-image module's delivered value is an image, and an image is the one
// thing a tag assertion cannot check: `og:image` naming a URL says nothing
// about whether the bytes at that URL are a card, are the right size, or were
// composed on this site's own base raster. These functions read the published
// file instead.
//
// Scope is deliberately narrow. This suite composes PNG cards only, so the
// sniffer accepts PNG and rejects everything else by throwing -- which is
// itself the "the URL names a PNG" assertion -- and the decoder handles the
// one PNG shape Hugo emits for a filtered image (8-bit, non-interlaced, no
// palette). Every other shape is a loud failure rather than a silent
// mis-decode. `node:zlib` covers the inflate, so the suite keeps its no
// dependency, no lockfile, no `npm ci` posture.
//
// Golden-image diffing would be the alternative and is not used: a golden
// image fails on any encoder or antialiasing change, says nothing about which
// property broke, and can only be regenerated by the code under test.
import {inflateSync} from 'node:zlib';

// Header fields read from the bytes on disk, never from a decoder's opinion.
export function sniffPng(buf) {
  if (
    buf.length <= 33 ||
    buf.readUInt32BE(0) !== 0x89504e47 ||
    buf.readUInt32BE(4) !== 0x0d0a1a0a
  ) {
    throw new Error(`not a PNG (leading bytes ${buf.subarray(0, 8).toString('hex')})`);
  }
  if (buf.subarray(12, 16).toString('latin1') !== 'IHDR')
    throw new Error('PNG without a leading IHDR');
  return {
    format: 'png',
    width: buf.readUInt32BE(16),
    height: buf.readUInt32BE(20),
    bitDepth: buf[24],
    colorType: buf[25],
    interlace: buf[28],
  };
}

export function decodePng(buf) {
  const head = sniffPng(buf);
  if (head.bitDepth !== 8) throw new Error(`bit depth ${head.bitDepth}: expected 8`);
  if (head.interlace !== 0) throw new Error('interlaced PNG');
  const channels = {0: 1, 2: 3, 4: 2, 6: 4}[head.colorType];
  if (!channels)
    throw new Error(`color type ${head.colorType} (a palette carries no direct samples)`);

  const parts = [];
  for (let off = 8; off + 8 <= buf.length; ) {
    const len = buf.readUInt32BE(off);
    const type = buf.subarray(off + 4, off + 8).toString('latin1');
    if (type === 'IDAT') parts.push(buf.subarray(off + 8, off + 8 + len));
    if (type === 'IEND') break;
    off += 12 + len;
  }
  const raw = inflateSync(Buffer.concat(parts));
  const {width, height} = head;
  const stride = width * channels;
  if (raw.length !== height * (stride + 1)) {
    throw new Error(`inflated ${raw.length} bytes, expected ${height * (stride + 1)}`);
  }

  // Undo the per-row filters (PNG specification, section 9).
  const data = Buffer.alloc(height * stride);
  let prev = Buffer.alloc(stride);
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)];
    const line = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    const cur = data.subarray(y * stride, (y + 1) * stride);
    for (let i = 0; i < stride; i++) {
      const a = i >= channels ? cur[i - channels] : 0;
      const b = prev[i];
      const c = i >= channels ? prev[i - channels] : 0;
      let value;
      switch (filter) {
        case 0:
          value = line[i];
          break;
        case 1:
          value = line[i] + a;
          break;
        case 2:
          value = line[i] + b;
          break;
        case 3:
          value = line[i] + ((a + b) >> 1);
          break;
        case 4: {
          const p = a + b - c;
          const pa = Math.abs(p - a);
          const pb = Math.abs(p - b);
          const pc = Math.abs(p - c);
          value = line[i] + (pa <= pb && pa <= pc ? a : pb <= pc ? b : c);
          break;
        }
        default:
          throw new Error(`unknown PNG filter ${filter} on row ${y}`);
      }
      cur[i] = value & 0xff;
    }
    prev = cur;
  }
  return {width, height, channels, data};
}

export function pixel(img, x, y) {
  const i = (y * img.width + x) * img.channels;
  const d = img.data;
  if (img.channels >= 3) {
    return {r: d[i], g: d[i + 1], b: d[i + 2], a: img.channels === 4 ? d[i + 3] : 255};
  }
  return {r: d[i], g: d[i], b: d[i], a: img.channels === 2 ? d[i + 1] : 255};
}

export const hex = ({r, g, b}) =>
  `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`;

const differs = (p, q, tolerance) =>
  Math.abs(p.r - q.r) + Math.abs(p.g - q.g) + Math.abs(p.b - q.b) > tolerance;

// Contiguous runs of rows carrying ink, measured against the base color. One
// band is one drawn line, so a line count and a line's horizontal extent are
// both readable without recognizing a single glyph.
export function inkBands(img, {base = pixel(img, 0, 0), tolerance = 30} = {}) {
  const bands = [];
  let open = null;
  for (let y = 0; y < img.height; y++) {
    let count = 0;
    let minX = Infinity;
    let maxX = -1;
    for (let x = 0; x < img.width; x++) {
      if (differs(pixel(img, x, y), base, tolerance)) {
        count += 1;
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
      }
    }
    if (count > 0) {
      if (open) {
        open.bottom = y;
        open.left = Math.min(open.left, minX);
        open.right = Math.max(open.right, maxX);
        open.pixels += count;
      } else {
        open = {top: y, bottom: y, left: minX, right: maxX, pixels: count};
      }
    } else if (open) {
      bands.push(open);
      open = null;
    }
  }
  if (open) bands.push(open);
  return bands;
}
