/* global Buffer */
// The measuring instrument. A card is a raster, so a spec that only checks a
// file exists proves nothing about what was drawn: these functions read the
// bytes on disk and turn them into the few properties a card actually
// promises -- its format and dimensions, which background it was composed on,
// how many lines of text were laid down, where they start and end, what color
// they were drawn in, and where an overlay landed.
//
// node:zlib only, no dependency. Hugo emits one PNG shape for a filtered card
// (8-bit, non-interlaced, a single IDAT chain), and the guards below turn any
// other shape into a loud failure rather than a silent mis-decode.
//
// Golden-image diffing is deliberately not used: a golden fails on any
// antialiasing or encoder change, says nothing about WHICH property broke, and
// has to be regenerated by the very code it is meant to check.
import {inflateSync} from 'node:zlib';

// ---- Header sniffing: the bytes on disk, never a decoder's opinion. A module
// that RETURNS 1200x630 and DRAWS 1200x628 satisfies every consumer-side check
// and none of these.
export function sniff(buf) {
  if (buf.length > 33 && buf.readUInt32BE(0) === 0x89504e47 && buf.readUInt32BE(4) === 0x0d0a1a0a) {
    if (buf.subarray(12, 16).toString('latin1') !== 'IHDR')
      throw new Error('PNG without a leading IHDR');
    return {
      format: 'png',
      width: buf.readUInt32BE(16),
      height: buf.readUInt32BE(20),
      bitDepth: buf[24],
      colorType: buf[25],
      interlace: buf[28],
    };
  }
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let off = 2;
    while (off + 9 < buf.length) {
      if (buf[off] !== 0xff) {
        off += 1;
        continue;
      }
      const marker = buf[off + 1];
      if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
        off += 2;
        continue;
      }
      const segment = buf.readUInt16BE(off + 2);
      const isFrame =
        marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
      if (isFrame) {
        return {
          format: 'jpeg',
          width: buf.readUInt16BE(off + 7),
          height: buf.readUInt16BE(off + 5),
          bitDepth: buf[off + 4],
          progressive: marker === 0xc2,
        };
      }
      off += 2 + segment;
    }
    throw new Error('JPEG carrying no frame header');
  }
  if (
    buf.length > 30 &&
    buf.subarray(0, 4).toString('latin1') === 'RIFF' &&
    buf.subarray(8, 12).toString('latin1') === 'WEBP'
  ) {
    const kind = buf.subarray(12, 16).toString('latin1');
    if (kind === 'VP8X')
      return {
        format: 'webp',
        variant: 'extended',
        width: buf.readUIntLE(24, 3) + 1,
        height: buf.readUIntLE(27, 3) + 1,
      };
    if (kind === 'VP8L') {
      const bits = buf.readUInt32LE(21);
      return {
        format: 'webp',
        variant: 'lossless',
        width: (bits & 0x3fff) + 1,
        height: ((bits >> 14) & 0x3fff) + 1,
      };
    }
    if (kind === 'VP8 ')
      return {
        format: 'webp',
        variant: 'lossy',
        width: buf.readUInt16LE(26) & 0x3fff,
        height: buf.readUInt16LE(28) & 0x3fff,
      };
    throw new Error(`WebP carrying an unknown chunk ${JSON.stringify(kind)}`);
  }
  throw new Error(`not a PNG, JPEG or WebP (leading bytes ${buf.subarray(0, 8).toString('hex')})`);
}

// ---- Full PNG decode, node:zlib only.
export function decodePng(buf) {
  const head = sniff(buf);
  if (head.format !== 'png') throw new Error(`decodePng was handed a ${head.format}`);
  if (head.bitDepth !== 8) throw new Error(`bit depth ${head.bitDepth}: expected 8`);
  if (head.interlace !== 0) throw new Error('interlaced PNG');
  const channels = {0: 1, 2: 3, 4: 2, 6: 4}[head.colorType];
  if (!channels)
    throw new Error(`color type ${head.colorType} (a palette carries no direct samples)`);
  const parts = [];
  for (let off = 8; off + 8 <= buf.length; ) {
    const len = buf.readUInt32BE(off);
    const type = buf.subarray(off + 4, off + 8).toString('latin1');
    if (type === 'IDAT') parts.push(buf.subarray(off + 8, off + 8 + len));
    if (type === 'IEND') break;
    off += 12 + len;
  }
  const raw = inflateSync(Buffer.concat(parts));
  const {width, height} = head;
  const stride = width * channels;
  if (raw.length !== height * (stride + 1))
    throw new Error(`inflated ${raw.length} bytes, expected ${height * (stride + 1)}`);
  const data = Buffer.alloc(height * stride);
  let prev = Buffer.alloc(stride);
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)];
    const line = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    const cur = data.subarray(y * stride, (y + 1) * stride);
    for (let i = 0; i < stride; i++) {
      const a = i >= channels ? cur[i - channels] : 0;
      const b = prev[i];
      const c = i >= channels ? prev[i - channels] : 0;
      let value;
      switch (filter) {
        case 0:
          value = line[i];
          break;
        case 1:
          value = line[i] + a;
          break;
        case 2:
          value = line[i] + b;
          break;
        case 3:
          value = line[i] + ((a + b) >> 1);
          break;
        case 4: {
          const p = a + b - c;
          const pa = Math.abs(p - a);
          const pb = Math.abs(p - b);
          const pc = Math.abs(p - c);
          value = line[i] + (pa <= pb && pa <= pc ? a : pb <= pc ? b : c);
          break;
        }
        default:
          throw new Error(`unknown PNG filter ${filter} on row ${y}`);
      }
      cur[i] = value & 0xff;
    }
    prev = cur;
  }
  return {width, height, channels, data};
}

export function pixel(img, x, y) {
  const i = (y * img.width + x) * img.channels;
  const d = img.data;
  if (img.channels >= 3)
    return {r: d[i], g: d[i + 1], b: d[i + 2], a: img.channels === 4 ? d[i + 3] : 255};
  return {r: d[i], g: d[i], b: d[i], a: img.channels === 2 ? d[i + 1] : 255};
}

export const hex = ({r, g, b}) =>
  `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`;

const differs = (p, q, tolerance) =>
  Math.abs(p.r - q.r) + Math.abs(p.g - q.g) + Math.abs(p.b - q.b) > tolerance;

// Contiguous runs of rows carrying ink. One band is one drawn line, so a line
// COUNT is measured without reading a single glyph, and the distance between
// two band tops is the pitch the engine used, which recovers the size it fitted
// at: pitch = round(size * line_height).
export function inkBands(img, {base = pixel(img, 0, 0), tolerance = 30, region} = {}) {
  const x0 = region?.x ?? 0;
  const y0 = region?.y ?? 0;
  const x1 = region ? region.x + region.width : img.width;
  const y1 = region ? region.y + region.height : img.height;
  const bands = [];
  let open = null;
  for (let y = y0; y < y1; y++) {
    let count = 0;
    let minX = Infinity;
    let maxX = -1;
    for (let x = x0; x < x1; x++) {
      if (differs(pixel(img, x, y), base, tolerance)) {
        count += 1;
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
      }
    }
    if (count > 0) {
      if (open) {
        open.bottom = y;
        open.left = Math.min(open.left, minX);
        open.right = Math.max(open.right, maxX);
        open.pixels += count;
      } else open = {top: y, bottom: y, left: minX, right: maxX, pixels: count};
    } else if (open) {
      bands.push(open);
      open = null;
    }
  }
  if (open) bands.push(open);
  return bands;
}

export function inkPixels(img, {base = pixel(img, 0, 0), tolerance = 30, region} = {}) {
  const out = [];
  const x0 = region?.x ?? 0;
  const y0 = region?.y ?? 0;
  const x1 = region ? region.x + region.width : img.width;
  const y1 = region ? region.y + region.height : img.height;
  for (let y = y0; y < y1; y++)
    for (let x = x0; x < x1; x++) {
      const p = pixel(img, x, y);
      if (differs(p, base, tolerance)) out.push({x, y, ...p});
    }
  return out;
}

// The color the glyphs were actually drawn in: the ink pixel furthest from the
// base, which is a fully covered interior pixel rather than an antialiased
// edge. Hugo draws a color it cannot read as white and says nothing, so this
// is what stands between a color typo and a card of invisible text.
export function inkColor(img, opts = {}) {
  const base = opts.base ?? pixel(img, 0, 0);
  let best = null;
  let bestDistance = -1;
  for (const p of inkPixels(img, {...opts, base})) {
    const d = Math.abs(p.r - base.r) + Math.abs(p.g - base.g) + Math.abs(p.b - base.b);
    if (d > bestDistance) {
      bestDistance = d;
      best = p;
    }
  }
  return best && {r: best.r, g: best.g, b: best.b, a: best.a};
}

// Characters drawn on a band, for a MONOSPACE face: a constant advance divides
// the ink extent from the alignment anchor into a character count, so what a
// card says can be compared with what it was asked to say.
export function charsOn(band, {anchorX, advance}) {
  return Math.round((band.right - anchorX + 1) / advance);
}

// Pixels matching a flat color within a tolerance, used for an overlay whose
// own color appears nowhere else on the card.
export function countColor(img, {r, g, b}, {tolerance = 30, region} = {}) {
  let n = 0;
  const x0 = region?.x ?? 0;
  const y0 = region?.y ?? 0;
  const x1 = region ? region.x + region.width : img.width;
  const y1 = region ? region.y + region.height : img.height;
  for (let y = y0; y < y1; y++)
    for (let x = x0; x < x1; x++) {
      const p = pixel(img, x, y);
      if (Math.abs(p.r - r) + Math.abs(p.g - g) + Math.abs(p.b - b) <= tolerance) n += 1;
    }
  return n;
}

// The bounding box of every pixel matching a flat color, or null when the card
// carries none: an overlay's exact rectangle recovers the anchor arithmetic.
export function colorBounds(img, {r, g, b}, {tolerance = 30} = {}) {
  let box = null;
  for (let y = 0; y < img.height; y++)
    for (let x = 0; x < img.width; x++) {
      const p = pixel(img, x, y);
      if (Math.abs(p.r - r) + Math.abs(p.g - g) + Math.abs(p.b - b) > tolerance) continue;
      if (!box) box = {left: x, right: x, top: y, bottom: y, pixels: 0};
      box.left = Math.min(box.left, x);
      box.right = Math.max(box.right, x);
      box.top = Math.min(box.top, y);
      box.bottom = Math.max(box.bottom, y);
      box.pixels += 1;
    }
  return box;
}
